version: "3.9"
services:
  minecraft:
    build: .
    volumes:
      - .:/minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    deploy:
      resources:
        limits:
          memory: 1G
